drop database if exists Blood_Donation_Project;

create database Blood_Donation_Project;

use Blood_Donation_Project;


CREATE TABLE DONOR_PHONE (
  Phone_no VARCHAR(15) NOT NULL,
  DonorId VARCHAR(45) NOT NULL,
  PRIMARY KEY (Phone_no));


CREATE TABLE EMERGENCY_CONTACT_INFO (
  Phone_no VARCHAR(15) NOT NULL,
  Donor_id INT NOT NULL,
  Name VARCHAR(45) NULL,
  PRIMARY KEY (Phone_no,Donor_id));


CREATE TABLE EMERGENCY_CONTACT_EMAIL (
  Phone_no VARCHAR(15) NOT NULL,
  Donor_id INT NOT NULL,
  Email_id VARCHAR(45) NOT NULL,
  EMERGENCY_CONTACT_INFOcol VARCHAR(45) NULL,
  PRIMARY KEY (Email_id, Donor_id, Phone_no));

CREATE TABLE DBA_LOGIN_CREDENTIALS (
  DBA_id INT NOT NULL AUTO_INCREMENT,
  Email_id VARCHAR(45) NOT NULL UNIQUE,
  user_name VARCHAR(20) NOT NULL UNIQUE,
  Password VARCHAR(25) NOT NULL,
  PRIMARY KEY (DBA_id));
  
  
-- Constraints 


ALTER TABLE DONOR_PHONE
ADD FOREIGN KEY (DonorId)
  REFERENCES DONOR (Donor_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE EMERGENCY_CONTACT_INFO
ADD FOREIGN KEY (DonorId)
  REFERENCES DONOR (Donor_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE EMERGENCY_CONTACT_EMAIL
ADD FOREIGN KEY (DonorId,Phone_no)
  REFERENCES EMERGENCY_CONTACT_INFO (Donor_id,Phone_no)
  ON DELETE CASCADE
  ON UPDATE CASCADE;