// export const EmailRegex=\\
export const LoginUrl = "operator_login";
export const GuestBloodUnitUrl = "guest_user/blood";
export const AddBloodUnitUrl = ":operator_id/blood";
export const ExpiredBloodUnitUrl = ":operator_id/expired_blood";
export const BloodLimitUrl = ":operator_id/blood_limit";
export const AddBloodBankUrl = "bloodbank";
export const AddDonorUrl = "bloodbank/donor/add";
export const UpdateDonorUrl = "bloodbank/donor/update";
export const DeleteDonorUrl = "bloodbank/donor/delete";
export const GetDonorByEmailIdUrl = "bloodbank/donor";
export const AddOperatorUrl = "operator/signup";
export const UpdateOpeatorUrl = "operator";
export const AddEventUrl = "blood_donation_event";
export const GetAllEventsUrl = "/:operator_id/blood_donation_event/all";
export const AddBranchUrl = ":operator_id/branches";
export const GetBranchDetailUrl = ":operator_id/branch_info";