// export const EmailRegex=\\
export const LoginUrl='login';
export const getProjectListUrl='projects';//Get Method
export const createProjectUrl='project';//Post Method
export const createEnvironmentUrl='environment';//Post Method
export const getEnvironmentListUrl='project/:projectId/environments';//Get Method
export const createRequirementUrl='requirement';//Post Method
export const getRequirementListUrl='project/:projectId/requirements'
export const createVariableUrl='environment-variable';//Post Method
export const getVariableListUrl='environment/:environmentId/variables';//Get Method
export const getEnvironmentUserListUrl='project/:projectId/environmentusers'//Get Method
export const createEnvironmentUserUrl='environment-user';//Post Method
export const getEnvironmentListForDDLUrl='project/:projectId/environments-ddl';
export const getMetadataTemplatesDDLUrl='metadata-templates';
export const registerUrl='register';
export const getApplicationListUrl='metadata/:metadataId/applications';
export const createMetadataApplicationUrl='metadata-application';
export const getVersionListUrl='metadata-application/:applicationId/versions';
export const createMetadataVersionUrl='metadata-version';
export const getApplicationListForDDLUrl='metadata/:metadataId/applications-ddl';
export const getVersionListForDDLUrl='metadata-application/:applicationId/versions-ddl';
export const getChildrenForTreeUrl='groups'
export const createGroupUrl='group'
export const createActionUrl='action'
export const getActionListForDDLUrl='project/:projectId/actions-ddl'
export const gtActionsListUrl='project/:projectId/actions'
export const getFieldIdentifierListForDDLUrl='selenium-identifiers'
export const getSeleniumFunctionsListForDDLUrl='selenium-functions'
export const getFunctionsListForDDLUrl='functions-ddl'
export const createTestcaseUrl='testcase';